stages:
  - test_and_upload
  - name: publish
    if: NOT (type = pull_request)
branches:
    only:
      - develop
jobs:
  include:
    - os: osx
      stage: test_and_upload
      env:
        KBUILD=macos
        JAVA_OPTS=-Xmx2g
      language: java
      jdk: openjdk10
      before_install:
        - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
      install:
        - echo install
      before_script:
        - SET
        - echo $TRAVIS_BRANCH
        - echo $TRAVIS_PULL_REQUEST
        - echo xxx
        - chmod +x ./gradlew
      script:
        - |
          if [ $TRAVIS_BRANCH == "develop" && $TRAVIS_PULL_REQUEST == "false" ]; then

          fi